name: ez_english
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  provider: ^6.0.5
  easy_localization: ^3.0.6
  flutter_svg: ^2.0.9
  flutter_tts: ^4.0.2
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_azure_tts: ^0.1.3
  cloud_text_to_speech: ^2.3.0
  # audioplayers: ^5.2.1
  flutter_dotenv: ^5.1.0
  just_audio: ^0.9.37
  http: ^0.13.6
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  go_router: ^14.1.1
  firebase_auth: ^4.19.5
  email_validator: ^2.1.17
  cloud_firestore: ^4.17.3
  excel: ^4.0.3
  youtube_player_flutter: ^9.0.1
  firebase_storage: ^11.7.7
  path: ^1.9.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  rename: ^3.0.2
  change_app_package_name: ^1.2.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo2.png
  android_12:
    image: assets/images/logo2.png
    android: true
    ios: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/questions.xlsx
    - assets/questions/images/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter-Regular.ttf
        - asset: assets/fonts/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/Inter-Black.ttf
          weight: 900
